apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webtest 
spec: 
  replicas: 3 
  selector:
    matchLabels: 
      app: webtest
  template:
    metadata:
      labels:
        app: webtest
    spec:
      initContainers: # 保证myslq 启动，在启动网站
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup mysql-service; do echo waiting for mysql-service; sleep 2; done;']
      containers:
      - image: registry.cn-chengdu.aliyuncs.com/kyrie-test/webtest:v2
        imagePullPolicy: IfNotPresent
        name: webtest
        ports: 
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Deployment"

        readinessProbe:  # 就绪探针
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 2

      imagePullSecrets:
      - name: webtest
---
apiVersion: v1
kind: Service 
metadata:
    name: webtest-service
spec:  
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30002
  selector:
    app: webtest