---
kind: PersistentVolume
apiVersion: v1
metadata: 
  name: mysql-pv
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath: 
    path: /mnt/c/docker/mysql/data
  
  #local:
   # path: /mnt/disks/vol1

---
kind: PersistentVolumeClaim
apiVersion:  v1
metadata: 
  name: mysql-pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: local-storage
  
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  namespace: data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer