apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: mysql-statefuleset-pv-0
  labels:
    type: local
spec:
  storageClassName: mysql-statefuleset-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/statefuleset/mysql"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: mysql-statefuleset-pv-1
  labels:
    type: local
spec:
  storageClassName: mysql-statefuleset-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/statefuleset/mysql"