apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers: 
      - name: mysql 
        image: mysql
        env:     
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports: 
        - containerPort: 3306
        volumeMounts: 
        - name: mysql-local-storage
          mountPath: /var/lib/mysql
      volumes: 
      - name: mysql-local-storage
        persistentVolumeClaim:
            claimName: mysql-pvc
        #hostPath: 
         # path: /mnt/c/docker/data

